# Basic Settings
spring.application.name=wallet-api
server.port=9090

# Database Connection (Injected by Docker/GitHub Secrets)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.override-with-generic-response=false

# Security / JWT (Injected by Docker/GitHub Secrets)
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000